name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: "13.203.161.198" # Replace with your EC2 instance's public IP
          username: "ubuntu"
          port: 22
          key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAQEA2pja40HsbKLHnEiCA0R3VUzg5RG9FWvVjDf5qCWuwEriZkWY1EoL
qQGYM9Y2WDY8Z3Y4r1a1U3AodcozOJobh9OsUG5koZ/vM7HpIGcYOuTvOTYa0UrkSWio2v
7rOOBgRu8vijwVNXir6vJFYzUS+nx1d7HA4MCRfVEpyBTTlS/dtkLH5tP1m8VpGVgNbkLJ
1CKb3MRnhOZBFboQ8yjqK+NulNXsVIfOwP5kqIvITw+lQO8Bjt/M5EvePsZKjr32OjqNog
l3HMpfjaIptXwibXeuR4B8PgbQP8OmNj63iuxXQMazGiE0VGhVwas2VxT6cH3o+buOwhfa
ealyy3SllwAAA8iICKIHiAiiBwAAAAdzc2gtcnNhAAABAQDamNrjQexsosecSIIDRHdVTO
DlEb0Va9WMN/moJa7ASuJmRZjUSgupAZgz1jZYNjxndjivVrVTcCh1yjM4mhuH06xQbmSh
n+8zsekgZxg65O85NhrRSuRJaKja/us44GBG7y+KPBU1eKvq8kVjNRL6fHV3scDgwJF9US
nIFNOVL922Qsfm0/WbxWkZWA1uQsnUIpvcxGeE5kEVuhDzKOor426U1exUh87A/mSoi8hP
D6VA7wGO38zkS94+xkqOvfY6Oo2iCXccyl+Noim1fCJtd65HgHw+BtA/w6Y2PreK7FdAxr
MaITRUaFXBqzZXFPpwfej5u47CF9p5qXLLdKWXAAAAAwEAAQAAAQAztHMVzPqMqaYYT8g8
2J13VjNdy2fToMmGnJjXTm56ulu5wB2JnSgL5j4niLQbAl0gRcTbqGFEZqOTVOvvp/f6FT
XNYoc3+Zn9Osg/K1N+Xrc865DFT3cW7AQApMpjjiMHtDyk8Fg96RiU/pAuCpg+GmE4mhla
sAHZx/BfjJmNUDCriXV7FDfWOYZ71QfQ4YH0T0sHx/ergLzmrzxIMzM4hVc2B7WES3j+44
5KIlqXv0d0ExrZ7238ZMbrTpNHKHHP3Q4Sa+QHYj20tcNyzsBbQ1eD6BAJJHEXoAm7+RuS
JUF+aYidUMJ2y10hRx3s+jK1e8XJG8b09BQxZAxWmAaxAAAAgQDDCjWC2q9fOd99Jy0dn+
3BWfs0nXdufS38qgCeRG9ynDkp2UY6i4S8ezd/28dktnxqFTSV3iE33zqXerpXPiSUGExX
MBCDnfyAMV1bLaqlPaDSZNgQV3rqFf1ZEI084iA5EysGPxNXcto4itOxlX7EsSrP/9D0mT
vx5hnftar38AAAAIEA8fNowte+WAdEEWRdnv0dEFkTTBOZ/AELV4X+ZmQUX5mHUaKzvz5l
Ftc0UpxMkE3TPCUt1h0bGfx9nGGRj+44KDUBiNUR1Qyrirgrt7C6S0UPfHURF7/Yhys9kU
qLh2cmowTFu+oP3JUJx9PzOzDYRxsS7Ka2nGdLy/OpyO+/1ccAAACBAOdKSx6GEX8et7aX
8goiWeeoiWf+sHgf2Dr2fhNrQrFFFloTlcKzJc9h9vh2tJvKzmMwvD3Ie0SuouSptrjD6v
tF/JW7iW6ywEalAFSyI9Oj13LLWV8Snz2xOl1rV+c7bqU4S7n2byHmqQcmsq9OCPtw/T38
77EAvAkELqbd43GxAAAAC25ldy1lYzIta2V5AQIDBAUGBw==
            -----END OPENSSH PRIVATE KEY-----
          script: |
            cd shad-backend || git clone https://github.com/amitmi7/shad-backend.git
            cd shad-backend
            git pull origin main
            npm install
            pm2 restart app.js || pm2 start app.js --name "shad-backend"
