name: Deploy Node.js to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Copy files to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: 13.203.161.198
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./"
          target: "/home/ubuntu/shad-backend"
          rm: true

      - name: Restart Node.js server
        uses: appleboy/ssh-action@master
        with:
          host: 13.203.161.198
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/shad-backend
            pm2 stop app.js || true
            pm2 start app.js
