name: Deploy to EC2 on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: 13.203.161.198               # Your EC2 public IP
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd shad-backend || git clone https://github.com/amitmi7/shad-backend.git
          cd shad-backend
          git pull origin main
          npm install
          pm2 restart app.js || pm2 start app.js --name "shad-backend"
