name: Production Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: "13.203.161.198"
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Add GitHub to known_hosts
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts

            # Navigate to home directory
            cd /home/ubuntu

            # Handle existing directory or clone the repository
            if [ -d "shad-backend" ]; then
              cd shad-backend
              git reset --hard
              git pull
            else
              git clone git@github.com:amitmi7/shad-backend.git
              cd shad-backend
            fi

            # Install dependencies
            npm install --production

            # Restart the application using PM2
            pm2 delete shad-backend || true
            pm2 start app.js --name "shad-backend" --update-env
            pm2 save

            echo "✅ Deployment completed successfully"
