name: Production Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: "13.203.161.198"
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Clean up previous deployment if exists
            rm -rf shad-backend || true
            
            # Clone fresh repository using SSH
            git clone https://github.com/amitmi7/shad-backend.git
            
            # Enter directory and install dependencies
            cd shad-backend
            npm install --production
            
            # Restart application
            pm2 delete shad-backend || true
            pm2 start app.js --name "shad-backend" --update-env
            pm2 save
            
            echo "✅ Deployment completed successfully"
