name: Deploy to EC2

on:
  push:
    branches:
      - main # This workflow runs when changes are pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Specifies the type of runner to use

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Checks out your repository code

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: "13.203.161.198"
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd shad-backend || git clone git@github.com:amitmi7/shad-backend.git
            cd shad-backend
            git pull origin main
            npm install
            pm2 restart app.js || pm2 start app.js --name "shad-backend"
