name: Production Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create .ssh directory
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Add GitHub to known_hosts
        run: |
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: SSH Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: "13.203.161.198"
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to the home directory
            cd /home/ubuntu

            # Handle repository: reset if exists or clone if missing
            if [ -d "shad-backend" ]; then
              cd shad-backend
              git reset --hard
              git pull
            else
              git clone git@github.com:amitmi7/shad-backend.git
              cd shad-backend
            fi

            # Install dependencies
            npm install --production

            # Clean up previous processes and start new one
            pm2 delete shad-backend || true
            pm2 start app.js --name "shad-backend" --update-env
            pm2 save

            # Confirm deployment success
            echo "✅ Deployment completed successfully"
